<a href="https://colab.research.google.com/github/gaiah-11/Repozitorij/blob/main/Predavanje_05_02_2026_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data processing tools


In [37]:
#IMport libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [64]:
#import dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/bio-chem-info/python_course/refs/heads/main/preprocess_data.csv')

In [77]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [66]:
#procesiranje podataka
a = dataset.tail(2).T
a

8        9
Country    Germany   France
Age           50.0     37.0
Salary     83000.0  67000.0
Purchased       No      Yes

In [67]:
#ispisi i transponiraj prva dva reda dataframe-a
dataset.head(2).T

0        1
Country     France    Spain
Age           44.0     27.0
Salary     72000.0  48000.0
Purchased       No      Yes

In [78]:
#indeksiranje - dohvacanje dijela podataka - radi sa []
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [79]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [51]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [52]:
#statistika dataframe-a
x.describe()

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [73]:
#koliko ima missing data u svakoj kategoriji
x.isna().sum()

Country    0
Age        1
Salary     1
dtype: int64

#Taking care of missing data

In [54]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [57]:
#nije u memoriji
#fillna - popunjavanje sa 0 - na=notanumber
x.fillna(0)

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [60]:
#0 nisu usle u radnu memoriju samo jednom napravljeno
x


Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [59]:
#x.fillna(0, inplace=True)   inplace=True da ude u radnu memoriju

In [61]:
x.fillna(0, inplace=True)
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [62]:
#x je updatean
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      0.0
5   France  35.0  58000.0
6    Spain   0.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [63]:
#ako ne zelim da ude u radnu memoriju ali zelim i drugi stvaram novi objekt
x1= x.fillna(0)

In [71]:
x.fillna(-99)

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0    -99.0
5   France  35.0  58000.0
6    Spain -99.0  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [110]:
from sklearn.impute import  SimpleImputer

#impute = popunjavanje praznih celija
#SimplImputer funkcija kojj se zadaje zadatak popunjavanja praznih celija
#missing values prepoznaje kao nan a strategija popunjavanja je median
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer

SimpleImputer(strategy='median')

In [111]:
#nauci primjeti obrazac = .fit
#zelimo obrazac primjenit na tablicu
imputer.fit()

TypeError: SimpleImputer.fit() missing 1 required positional argument: 'X'

In [112]:
imputer.fit(x[['Age','Salary']])
#.fit je naucio je mediane
#probir varijabla je uvijek [] ako ima lista vise od 1 onda su 2 []

imputer.statistics_
#izracunava mediane za dva stupca

array([3.8e+01, 6.1e+04])

In [113]:
x[['Age','Salary']].median()

Age          38.0
Salary    61000.0
dtype: float64

In [114]:
x_imputed = imputer.transform(x[['Age','Salary']])

In [115]:
imputer

SimpleImputer(strategy='median')

In [116]:
x_imputed

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 6.1e+04],
       [3.5e+01, 5.8e+04],
       [3.8e+01, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [117]:
#transformirat matricu u dataframe
#uzmi x_imputed kao data, imena stupaca su age i salary, indexi su indexi iz x
x_imp = pd.DataFrame(x_imputed,
                         columns=['Age','Salary'],
                         index=x.index)
x_imp

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  61000.0
5  35.0  58000.0
6  38.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [90]:
x_imp.median()

Age          38.0
Salary    61000.0
dtype: float64

In [103]:
#napravi dataframe gdje je -666 prazno polje
#napravi simpleimputer koji ce prepoznati -666 i napraviti zamjenu sa konstantnom vrijednosti vrjednosti

imputer = SimpleImputer(missing_values=-666.0, strategy='constant', fill_value=7)
imputer

SimpleImputer(fill_value=7, missing_values=-666.0, strategy='constant')

In [104]:
x.fillna(-666.0)

Country    Age   Salary
0   France   44.0  72000.0
1    Spain   27.0  48000.0
2  Germany   30.0  54000.0
3    Spain   38.0  61000.0
4  Germany   40.0   -666.0
5   France   35.0  58000.0
6    Spain -666.0  52000.0
7   France   48.0  79000.0
8  Germany   50.0  83000.0
9   France   37.0  67000.0

In [107]:
# First, ensure the missing values in the input data match what the imputer is expecting.
# Replace np.nan in 'Age' and 'Salary' columns with -666.0.
x_for_imputation = x[['Age','Salary']].fillna(-666.0)

# Now, fit the imputer on this prepared data.
imputer.fit(x_for_imputation)

# Finally, transform the data.
x_imputed = imputer.transform(x_for_imputation)

In [108]:
x_imputed

array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01, 7.0e+00],
       [3.5e+01, 5.8e+04],
       [7.0e+00, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [118]:
x_imp =pd.DataFrame(x_imputed,
                         columns=['Age','Salary'],
                         index=x.index)
x_imp

Age   Salary
0  44.0  72000.0
1  27.0  48000.0
2  30.0  54000.0
3  38.0  61000.0
4  40.0  61000.0
5  35.0  58000.0
6  38.0  52000.0
7  48.0  79000.0
8  50.0  83000.0
9  37.0  67000.0

In [122]:
#get_dummies - dataset, prema koloni country, drop_first=True znaci da mice prvi stupac informacija
x_encoded = pd.get_dummies(x, columns=['Country'],drop_first=True)
x_encoded

Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0            False          False
1  27.0  48000.0            False           True
2  30.0  54000.0             True          False
3  38.0  61000.0            False           True
4  40.0      NaN             True          False
5  35.0  58000.0            False          False
6   NaN  52000.0            False           True
7  48.0  79000.0            False          False
8  50.0  83000.0             True          False
9  37.0  67000.0            False          False

In [127]:
#true i force su posebni oblici podataka nsu rijeci ne treba ''
#zamijeni sve tre sa 1 sve false sa 0
#{} jer je dictionary odnosno key value pair - radimo parove
x_encoded= x_encoded.replace({True:1,False:0})
x_encoded


Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0                0              0
1  27.0  48000.0                0              1
2  30.0  54000.0                1              0
3  38.0  61000.0                0              1
4  40.0      NaN                1              0
5  35.0  58000.0                0              0
6   NaN  52000.0                0              1
7  48.0  79000.0                0              0
8  50.0  83000.0                1              0
9  37.0  67000.0                0              0

In [128]:
x

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [129]:
#od y napravit jedan stupac sa 0 i 1

In [130]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [135]:
y_encoded = pd.get_dummies(y)
y_encoded

No    Yes
0   True  False
1  False   True
2   True  False
3   True  False
4  False   True
5  False   True
6   True  False
7  False   True
8   True  False
9  False   True

In [134]:
y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [136]:
y_encoded= y_encoded.replace({True:1,False:0})
y_encoded

/tmp/ipython-input-1842726299.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y_encoded= y_encoded.replace({True:1,False:0})


No  Yes
0   1    0
1   0    1
2   1    0
3   1    0
4   0    1
5   0    1
6   1    0
7   0    1
8   1    0
9   0    1

In [140]:
y1 = y_encoded["No"]
y1.name = 'Purschase'
y1

0    1
1    0
2    1
3    1
4    0
5    0
6    1
7    0
8    1
9    0
Name: Purschase, dtype: int64

In [143]:
y1 = y.replace({'Yes':1,'No':0})
y1

/tmp/ipython-input-1691436157.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  y1 = y.replace({'Yes':1,'No':0})


0    0
1    1
2    0
3    0
4    1
5    1
6    0
7    1
8    0
9    1
Name: Purchased, dtype: int64

SPliting dataset into treaining test and test set

In [153]:
#od dvije matrice radim 4 jedna ce bit ya ucenje druga za ispitivanje
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x_encoded, y_encoded, test_size = 0.25, random_state = 42)

In [150]:
print(x_train)

    Age   Salary  Country_Germany  Country_Spain
0  44.0  72000.0                0              0
7  48.0  79000.0                0              0
2  30.0  54000.0                1              0
9  37.0  67000.0                0              0
4  40.0      NaN                1              0
3  38.0  61000.0                0              1
6   NaN  52000.0                0              1


In [151]:
print(x_test)

    Age   Salary  Country_Germany  Country_Spain
8  50.0  83000.0                1              0
1  27.0  48000.0                0              1
5  35.0  58000.0                0              0


In [152]:
print(y_train)

   No  Yes
0   1    0
7   0    1
2   1    0
9   0    1
4   0    1
3   1    0
6   1    0


Feature scaling

In [154]:
x_train.describe()

Age        Salary  Country_Germany  Country_Spain
count   6.000000      6.000000         7.000000       7.000000
mean   39.500000  64166.666667         0.285714       0.285714
std     6.188699  10496.030996         0.487950       0.487950
min    30.000000  52000.000000         0.000000       0.000000
25%    37.250000  55750.000000         0.000000       0.000000
50%    39.000000  64000.000000         0.000000       0.000000
75%    43.000000  70750.000000         0.500000       0.500000
max    48.000000  79000.000000         1.000000       1.000000

In [162]:
#ako imamo razlicite skale nemamo iste doprinose u grupama
#stavimo da sve npr idu od 5-100 da se mogu usporedivat
#MinMAxScaler sve ce bit na skali od 0 do 1
#fit_transform istovremeno uci i primjenjuje
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc

StandardScaler()

In [160]:
sc.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [ ]:
sc.fit(x_train)

In [165]:
#Fit 'sc' with 'x_train' to compute the means.
#The StandardScaler object 'sc' needs to be fitted before accessing 'mean_'.

sc.fit(x_train)
sc.mean_


array([3.95000000e+01, 6.41666667e+04, 2.85714286e-01, 2.85714286e-01])

In [170]:
#izracunaj std
x_train.std()

Age                    6.188699
Salary             10496.030996
Country_Germany        0.487950
Country_Spain          0.487950
dtype: float64

In [171]:
sc.var_

array([3.19166667e+01, 9.18055556e+07, 2.04081633e-01, 2.04081633e-01])

In [172]:
x_train.var()

Age                3.830000e+01
Salary             1.101667e+08
Country_Germany    2.380952e-01
Country_Spain      2.380952e-01
dtype: float64

In [183]:
x_train_sc = sc.fit_transform(x_train)
x_test=sc.transform(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [184]:
x_train_sc = pd.DataFrame(x_train_sc, columns=x_train.columns, index=x_train.index)
x_train_sc

Age    Salary  Country_Germany  Country_Spain
0  0.796533  0.817546        -0.632456      -0.632456
7  1.504562  1.548119        -0.632456      -0.632456
2 -1.681570 -1.061070         1.581139      -0.632456
9 -0.442518  0.295708        -0.632456      -0.632456
4  0.088504       NaN         1.581139      -0.632456
3 -0.265511 -0.330497        -0.632456       1.581139
6       NaN -1.269805        -0.632456       1.581139

In [190]:
#ravnopravni podatci moze biti x standardnih devijacija gore i x stdev dole
x_train_sc.describe()

Age        Salary  Country_Germany  Country_Spain
count  6.000000e+00  6.000000e+00     7.000000e+00       7.000000
mean  -3.700743e-17  2.220446e-16     3.172066e-17       0.000000
std    1.095445e+00  1.095445e+00     1.080123e+00       1.080123
min   -1.681570e+00 -1.269805e+00    -6.324555e-01      -0.632456
25%   -3.982665e-01 -8.784269e-01    -6.324555e-01      -0.632456
50%   -8.850366e-02 -1.739459e-02    -6.324555e-01      -0.632456
75%    6.195256e-01  6.870864e-01     4.743416e-01       0.474342
max    1.504562e+00  1.548119e+00     1.581139e+00       1.581139

In [189]:
x_train.describe()

Age        Salary  Country_Germany  Country_Spain
count   6.000000      6.000000         7.000000       7.000000
mean   39.500000  64166.666667         0.285714       0.285714
std     6.188699  10496.030996         0.487950       0.487950
min    30.000000  52000.000000         0.000000       0.000000
25%    37.250000  55750.000000         0.000000       0.000000
50%    39.000000  64000.000000         0.000000       0.000000
75%    43.000000  70750.000000         0.500000       0.500000
max    48.000000  79000.000000         1.000000       1.000000

Proba 2 sa MinMAxScaler

In [197]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler()
mm

MinMaxScaler()

In [198]:
mm.fit(x_train)

MinMaxScaler()

In [199]:
x_train_mm = mm.fit_transform(x_train)
x_test=mm.transform(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [200]:
x_train_mm = pd.DataFrame(x_train_mm, columns=x_train.columns, index=x_train.index)

In [201]:
x_train_mm

Age    Salary  Country_Germany  Country_Spain
0  0.777778  0.740741              0.0            0.0
7  1.000000  1.000000              0.0            0.0
2  0.000000  0.074074              1.0            0.0
9  0.388889  0.555556              0.0            0.0
4  0.555556       NaN              1.0            0.0
3  0.444444  0.333333              0.0            1.0
6       NaN  0.000000              0.0            1.0

In [ ]:
#xmin se pretvara u 0 xmax se pretvara u 1