<a href="https://colab.research.google.com/github/gaiah-11/Repozitorij/blob/Kopija-repo/Predavanje_03_02_2026_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Predavanje


In [219]:
12

12

In [220]:
type(12)

int

In [266]:
type(12,5)

TypeError: type() takes 1 or 3 arguments

In [267]:
type(12.5)

float

In [270]:
type(Draga)

NameError: name 'Draga' is not defined

In [271]:
'apple'

'apple'

In [272]:
"apple"

'apple'

In [273]:
type(draga)

NameError: name 'draga' is not defined

In [274]:
False

False

In [275]:
3=4

SyntaxError: cannot assign to literal here. Maybe you meant '==' instead of '='? (ipython-input-1436796609.py, line 1)

In [276]:
dictionaries {}
list []
tuple ()


SyntaxError: invalid syntax (ipython-input-3067695636.py, line 1)

In [277]:
[1,2,3]

[1, 2, 3]

In [278]:
type([1,2,3])

list

In [279]:
1,2,3

(1, 2, 3)

In [280]:
t = [1,2,3]

In [281]:
t

[1, 2, 3]

In [282]:
plants = {"apple": "a fruit", "banana": "a herb"}

In [283]:
type({"apple": "a fruit", "banana": "a herb"})

dict

In [284]:
3 < 5

True

In [285]:
plants['banana']

'a herb'

In [286]:
import pandas as pd


In [287]:
pd.DataFrame(plants, [0,1])

apple  banana
0  a fruit  a herb
1  a fruit  a herb

In [288]:
squares = [1,4,9,16,25]

In [289]:
type(squares)

list

In [290]:
squares

[1, 4, 9, 16, 25]

In [291]:
squares[4]

25

In [292]:
squares[-2]

16

In [293]:
squares[:]

[1, 4, 9, 16, 25]

In [294]:
squares[1:]

[4, 9, 16, 25]

In [295]:
squares[1:3]

[4, 9]

In [296]:
squares + [36,49,64,81,100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [297]:
squares

[1, 4, 9, 16, 25]

In [298]:
sq2 = squares + [36,49,64,81,100]

In [299]:
animals = ['cat', 'dog', 'bird']

In [300]:
animals[0]

'cat'

In [301]:
len(sq2)

10

In [302]:
len(sq2[:5])

5

In [303]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [304]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [305]:
letters[1:2] = [1,2,3,4,5]

In [306]:
letters

['a', 1, 2, 3, 4, 5, 'c', 'd', 'e', 'f', 'g']

In [307]:
len(letters)

11

In [308]:
abs(1)

1

In [309]:
abs(-10)

10

In [310]:
import operator

In [311]:
1 + 3

4

In [312]:
operator.add(1,3)

4

In [313]:
operator.sub(1,10)

-9

In [314]:
operator.eq(10,10)

True

In [315]:
##Print

##Print

In [316]:
print(1)

1


In [317]:
print('This'+'' + 'is'+''+'a'+''+'full'+''+'sentence')

Thisisafullsentence


In [318]:
print('This'+' ' + 'is'+' '+'a'+' '+'full'+' '+'sentence')

This is a full sentence


In [319]:
print('This', 'is', 'a', 'full', 'sentence')

This is a full sentence


In [320]:
print('Micheal', 'is', 'helping')

Micheal is helping


In [321]:
print(sq2[1:5])

[4, 9, 16, 25]


In [322]:
None

In [323]:
type(None)

NoneType

In [324]:
def pozdrav(ime):
  print('Pozdrav','kako','si', ime,'?')

In [325]:
pozdrav('Anja')

Pozdrav kako si Anja ?


In [326]:
def hallo(ti):
  print('Hallo', 'si', 'ti','dobro',ti,'?')

In [327]:
hallo(Drago)

NameError: name 'Drago' is not defined

In [328]:
hallo('Drago')

Hallo si ti dobro Drago ?


In [329]:
def funkcija(x):
  '''This function multiplies its argument by 2.
  Written by Gaia'''
  result = x*2
  return result

In [330]:
funkcija(4)

8

In [331]:
fukncija(5)

NameError: name 'fukncija' is not defined

In [332]:
funkcija(3.15)

6.3

In [333]:
type(funkcija)

function

In [334]:
import math

In [335]:
def ph(c):
  '''This function calculates the pH of a solution.
  It uses the concentration of the H+ in mol/L.
  It returns the pH.'''
  ph = -math.log10(c)
  return ph

In [336]:
ph(0.001)

3.0

In [337]:
def ph1(c):
  return -math.log10(c)

In [338]:
ph1(0.001)

3.0

In [339]:
def task(x,y):
  '''definicija'''
  print('This is the log10 of x', math.log10(x))
  print('This is the log10 of y', math.log10(y))
  new_number = math.log10(x) + math.log10(y)
  print('The sum result of both log10 is below:')
  return new_number

In [340]:
tsk(1000, 2.73)

NameError: name 'tsk' is not defined

In [341]:
task(1000, 2.73)

This is the log10 of x 3.0
This is the log10 of y 0.436162647040756
The sum result of both log10 is below:


3.436162647040756

In [342]:
def konverzija(euro):
  dkk = euro*7.55
  return dkk

In [343]:
konverzija(8)

60.4

In [344]:
def plus(a,b,c,d,):
  suma = a + b + c + d
  return suma

In [345]:
plus(1,2,3,4)

10

In [346]:
= i ==

SyntaxError: invalid syntax (ipython-input-318240625.py, line 1)

In [347]:
1==1

True

In [348]:
width = 20
height = 5*90
height, width

(450, 20)

In [349]:
width == 30

False

In [350]:
width ==20

True

In [351]:
width==20

True

In [352]:
width = 30

In [353]:
width==30

True

In [354]:
width==20

False

In [355]:
cp1='Tomo'
cp2='Maria'
cpa,cp2

NameError: name 'cpa' is not defined

In [356]:
cp1,cp2

('Tomo', 'Maria')

In [357]:
width==height

False

In [358]:
cp1!=cp2

True

##is & is not

In [359]:
5 is 4

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-171648558.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 4


False

In [360]:
5 is 5

<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
/tmp/ipython-input-1783323536.py:1: SyntaxWarning: "is" with 'int' literal. Did you mean "=="?
  5 is 5


True

In [361]:
width is height

False

In [362]:
width i snot height

SyntaxError: invalid syntax (ipython-input-2331987441.py, line 1)

In [363]:
width is not height

True

In [364]:
squares

[1, 4, 9, 16, 25]

In [365]:
squares.append(36)

In [366]:
squares

[1, 4, 9, 16, 25, 36]

In [367]:
squares2= squares+[36]

In [368]:
squares2

[1, 4, 9, 16, 25, 36, 36]

In [369]:
new_list.append(36)

In [370]:
last_list=squares.copy()
last_list

[1, 4, 9, 16, 25, 36]

In [371]:
squares.append(10)

In [372]:
last_list

[1, 4, 9, 16, 25, 36]

In [373]:
squares

[1, 4, 9, 16, 25, 36, 10]

In [374]:
print('Particpiants in the course were', cp1, 'and', cp2, '.')

Particpiants in the course were Tomo and Maria .


In [375]:
print('Particpiants in the course were %s and %s.'
      %(cp1, cp2))

Particpiants in the course were Tomo and Maria.


In [376]:
sample = 'u553'
conc = 0.016
print('In a sample %s we found %s mg/L of drugs' %(sample, conc))

In a sample u553 we found 0.016 mg/L of drugs


In [377]:
print(f'In a sample {sample} we found {conc} mg/L of drugs.')

In a sample u553 we found 0.016 mg/L of drugs.


In [378]:
def bmi (w, h):
  bmi = w/h**2
  return bmi

In [379]:
bmi(w=65, h=1.64)

24.167162403331353

In [380]:
bmi(65, 1.64)

24.167162403331353

##c1*v1=c2*v2

In [381]:
def diluter(c1, v1=1, v2=2):
  '''Calculating dilution
  return c2'''
  c2 = c1*v1/v2
  return c2

In [382]:
diluter()

TypeError: diluter() missing 1 required positional argument: 'c1'

In [383]:
diluter(0.5)

0.25

In [384]:
help(diluter)

Help on function diluter in module __main__:

diluter(c1, v1=1, v2=2)
    Calculating dilution
    return c2



In [385]:
diluter(2)

1.0

In [386]:
diluter(2,1,3)

0.6666666666666666

In [387]:
def factor_corrections(c, f=1):
  cond = c*f
  return conc

In [388]:
factor_corrections(0.002,0.01)

0.016

In [389]:
factor_corrections(0.002)

0.016

In [390]:
help(factor_corrections)

Help on function factor_corrections in module __main__:

factor_corrections(c, f=1)



In [391]:
def something(a=1, b=2, c=3):
  return (a,b,c)

In [392]:
something

<function __main__.something(a=1, b=2, c=3)>

In [393]:
something()

(1, 2, 3)

In [394]:
something(10,10)

(10, 10, 3)

In [395]:
factor_corrections(0.002, 0.03)

0.016

In [396]:
factor_corrections(0.002, f=0.03)

0.016

In [397]:
factor_corrections(c=0.002, f=7)

0.016

In [398]:
factor_corrections(f=7, c=0.002)

0.016

In [399]:
something(5,5,c=5)

(5, 5, 5)

In [400]:
something(a=9)

(9, 2, 3)

In [401]:
def sum(a,b):
  return a+b

def adding3(a,b,c,):
  return sum(a,b)+c

In [402]:
adding3(1,2,3)

6

##For

In [414]:
Friend = ['Micheal', 'Tomo', 'Maria', 'Peter']

In [404]:
for person in Friend:
  print(person)

Micheal
Tomo
Maria
Peter


In [405]:
bmi

<function __main__.bmi(w, h)>

In [406]:
help(bmi)

Help on function bmi in module __main__:

bmi(w, h)



In [416]:
weights = [80,90,55,70]
heights = [1.8,2.0,1.6,1.55]

for x, Friend in enumerate(Friend):
  bmi_person = bmi(weights[x], heights[x])
  print(f'The BMI of {Friend} is {bmi_person}')

The BMI of Micheal is 24.691358024691358
The BMI of Tomo is 22.5
The BMI of Maria is 21.484374999999996
The BMI of Peter is 29.1363163371488


In [418]:
print(f'{Friend} has the bmi of {bmi_person}')

Peter has the bmi of 29.1363163371488


In [412]:
bmi

<function __main__.bmi(w, h)>

In [413]:
for x in squares:
  print('Element is %s' %x)

Element is 1
Element is 4
Element is 9
Element is 16
Element is 25
Element is 36
Element is 10


In [419]:
for number in squares:
  print(number)

1
4
9
16
25
36
10


In [420]:
Particpiants=[cp1, cp2]

In [421]:
Particpiants

['Tomo', 'Maria']

In [424]:
for name in Particpiants:
  print(name)

Tomo
Maria


In [425]:
for position in range(len(Particpiants)):
  print(position)

0
1


In [426]:
for number, element in enumerate(Particpiants):
  print(number, element)

0 Tomo
1 Maria


In [427]:
for number,element in enumerate(squares):
  print(number, element)

0 1
1 4
2 9
3 16
4 25
5 36
6 10


In [428]:
 squares

[1, 4, 9, 16, 25, 36, 10]

In [429]:
for number in squares:
  sq_root = math.sqrt(number)
  print(sq_root)

1.0
2.0
3.0
4.0
5.0
6.0
3.1622776601683795


##If else
 ==
 <
 <=
 !=

In [430]:
1 <=2

True

In [441]:
if 1 == 2:
  print('yes')
  print('da')
  print('ja')
if 1!= 2:
  print('no')
  print('nein')

no
nein


In [442]:
1 == 1

True

In [443]:
cp1 = ' Mila'
cp2 = 'Marko'

In [444]:
if cp1 == cp2:
  print('da')

In [447]:
if cp1 != cp2:
  print('da')

da


In [450]:
if cp1 == cp2:
    print('da')
else:
    print('ne')

ne


In [457]:
def check_gender_by_name(name):
  if name[-1]=="a":
    gener = 'female'
  elif name [-1]=='o':
    gender= 'male'
  else:
    gender = 'unkonwn'
  return gender

In [460]:
def check_gender_by_name(name):
  if name[-1]=="a":
    gender = 'female' # Corrected typo from 'gener' to 'gender'
  elif name [-1]=='o':
    gender= 'male'
  else:
    gender = 'unkonwn'
  return gender

check_gender_by_name('Lana')

'female'

In [461]:
check_gender_by_name('marko')

'male'

In [462]:
ph

<function __main__.ph(c)>

In [463]:
ph(0.001)

3.0

In [466]:
def ph_evaluator(c=0.001):
  '''Ph decision maker'''
  ph_value = ph(c)

  if ph_value < 7:
    decision = 'kiselo'
  else:
    decision = 'lužnato'
  return decision

In [467]:
ph_evaluator(9)


'kiselo'

In [468]:
def ph_evaluator(c=0.001):
  if ph(c) < 7:
    return 'kiselo'
  else:
    return 'lužnato'

conc_list = [0.001,0.01,0.1,1,10]
for solution in conc_list:
  print(ph_evaluator(solution))

kiselo
kiselo
kiselo
kiselo
kiselo


In [469]:
def test_if_else(a,b):
  '''a,b su argumenti
  return a>b or a is not >b'''
  if a>b:
    print(a,'>',b)
  else:
    print('%d is not > %d' %(a,b))

In [470]:
help(test_if_else)

Help on function test_if_else in module __main__:

test_if_else(a, b)
    a,b su argumenti
    return a>b or a is not >b



In [471]:
test_if_else(4,7)

4 is not > 7


In [472]:
test_if_else(5,1)

5 > 1


In [473]:
def rectangle_area(a,b):
  '''dokumentacija'''
  A=a*b
  if a ==b:
    print('kvadrat')
  else:
    print('pravokutnik')
  return A

In [474]:
rectangle_area(2,3)

pravokutnik


6

In [475]:
rectangle_area

<function __main__.rectangle_area(a, b)>

In [477]:
for letter in [1,2,3]:
  print('broj:', letter)

broj: 1
broj: 2
broj: 3


In [478]:
 x = 5

In [479]:
x

5

In [480]:
y=2

In [481]:
x+y

7

In [482]:
povrsina = rectangle_area(5,4)

pravokutnik


In [483]:
povrsina

20

In [484]:
(-3)**4

81

In [485]:
-(3**4)

-81

In [486]:
3*3.75/1.5

7.5

In [487]:
a = [4,5,6]
n = [1,2,3]

In [488]:
x =[a,n]

In [489]:
x

[[4, 5, 6], [1, 2, 3]]

In [490]:
import numpy as np

In [491]:
nums1 = [1,2,3,4,5]

In [492]:
nums1

[1, 2, 3, 4, 5]

In [493]:
nums2=np.array(nums1)

In [494]:
nums2

array([1, 2, 3, 4, 5])

In [495]:
type(nums1), type(nums2)

(list, numpy.ndarray)

In [496]:
max(nums1)

5

In [497]:
max(nums1)

5

In [498]:
min(nums1)

1

In [499]:
np.min(nums2)

np.int64(1)

In [500]:
x1 = np.array([1.3,0,2])
x1

array([1.3, 0. , 2. ])

In [501]:
x2 = np.array([1,0,2])

In [502]:
x2

array([1, 0, 2])

In [503]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [504]:
x1.dtype
x2.dtype

dtype('int64')

In [505]:
x1.dtype

dtype('float64')

In [506]:
x2.dtype

dtype('int64')

In [512]:
x2 = np.arange(20,50,2)

In [513]:
x2

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [514]:
x2 = np.linspace(10,20,10, endpoint=False)

In [515]:
x2

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [516]:
nule = np.zeros((5,3))
nule.shape

(5, 3)

In [517]:
nule

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [518]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [522]:
x4 = np.random.random((3,10))

In [523]:
x4

array([[0.13561031, 0.38172866, 0.30648697, 0.30442373, 0.70136444,
        0.54764931, 0.83614062, 0.55645441, 0.03964446, 0.14906085],
       [0.44270139, 0.54132583, 0.4912548 , 0.70497934, 0.20575176,
        0.58255325, 0.46376532, 0.15415516, 0.06179687, 0.02479872],
       [0.38654191, 0.86614969, 0.99156822, 0.0816346 , 0.85469244,
        0.77110884, 0.4062951 , 0.79331591, 0.75561636, 0.00117548]])

In [524]:
x4

array([[0.13561031, 0.38172866, 0.30648697, 0.30442373, 0.70136444,
        0.54764931, 0.83614062, 0.55645441, 0.03964446, 0.14906085],
       [0.44270139, 0.54132583, 0.4912548 , 0.70497934, 0.20575176,
        0.58255325, 0.46376532, 0.15415516, 0.06179687, 0.02479872],
       [0.38654191, 0.86614969, 0.99156822, 0.0816346 , 0.85469244,
        0.77110884, 0.4062951 , 0.79331591, 0.75561636, 0.00117548]])

In [525]:
pd.DataFrame(x4)

0         1         2         3         4         5         6  \
0  0.135610  0.381729  0.306487  0.304424  0.701364  0.547649  0.836141   
1  0.442701  0.541326  0.491255  0.704979  0.205752  0.582553  0.463765   
2  0.386542  0.866150  0.991568  0.081635  0.854692  0.771109  0.406295   

          7         8         9  
0  0.556454  0.039644  0.149061  
1  0.154155  0.061797  0.024799  
2  0.793316  0.755616  0.001175

In [526]:
x4.dtype

dtype('float64')

In [527]:
x4.shape

(3, 10)

In [528]:
x4.reshape

<function ndarray.reshape>

In [529]:
x4.reshape(10,3)

array([[0.13561031, 0.38172866, 0.30648697],
       [0.30442373, 0.70136444, 0.54764931],
       [0.83614062, 0.55645441, 0.03964446],
       [0.14906085, 0.44270139, 0.54132583],
       [0.4912548 , 0.70497934, 0.20575176],
       [0.58255325, 0.46376532, 0.15415516],
       [0.06179687, 0.02479872, 0.38654191],
       [0.86614969, 0.99156822, 0.0816346 ],
       [0.85469244, 0.77110884, 0.4062951 ],
       [0.79331591, 0.75561636, 0.00117548]])

In [530]:
x4.T

array([[0.13561031, 0.44270139, 0.38654191],
       [0.38172866, 0.54132583, 0.86614969],
       [0.30648697, 0.4912548 , 0.99156822],
       [0.30442373, 0.70497934, 0.0816346 ],
       [0.70136444, 0.20575176, 0.85469244],
       [0.54764931, 0.58255325, 0.77110884],
       [0.83614062, 0.46376532, 0.4062951 ],
       [0.55645441, 0.15415516, 0.79331591],
       [0.03964446, 0.06179687, 0.75561636],
       [0.14906085, 0.02479872, 0.00117548]])

In [532]:
np.arange(2,20).reshape(2,3,3).T

array([[[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]],

       [[ 4, 13],
        [ 7, 16],
        [10, 19]]])

In [533]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [534]:
A = np.arange(9).reshape(3,3)

In [535]:
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [536]:
I@A

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [537]:
A@A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])